symbolinfo/markets/urls.py
from django.urls import path

from . import views

app_name = 'markets'

urlpatterns = [
    path('', views.index, name='index'),
    path('markets/<str:name>/', views.market, name='market'),
]

symbolinfo/symbolinfo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('markets.urls', namespace='markets')),
    path('admin/', admin.site.urls),
]

symbolinfo/markets/models.py
from django.db import models


class Market(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return str(self.name)


class SymbolInfo(models.Model):
    name = models.CharField(max_length=20)
    market = models.ForeignKey(
        Market,
        on_delete=models.CASCADE,
        related_name='symbols',
    )
    lot_size = models.IntegerField(default=1)

symbolinfo/markets/views.py
from django.shortcuts import render, get_object_or_404

from .models import Market, SymbolInfo

SYMBOLS_PER_PAGE = 10


def index(request):
    template = 'markets/index.html'
    symbol_infos = SymbolInfo.objects.order_by('name')[:SYMBOLS_PER_PAGE]
    context = {
        'symbol_infos': symbol_infos
    }
    return render(request, template, context)


def market(request, name):
    template = 'markets/market.html'
    market = get_object_or_404(Market, name=name)
    symbol_infos = market.symbols.all().order_by('name')
    context = {
        'market': market,
        'symbol_infos': symbol_infos
    }
    return render(request, template, context)

symbolinfo/templates/base.html
{% load static %}
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}Не найдено{% endblock %}</title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      <div class="container py-5">
        {% block content %}Не найдено{% endblock %}
      </div>
    </main>
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

symbolinfo/templates/includes/footer.html
<p>© 2021 Copyright <span style="color:red">Symbol</span>Info</p>

symbolinfo/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'markets:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Symbol</span>Info</a>
    </a>
  </div>
</nav>

symbolinfo/templates/markets/index.html
{% extends 'base.html' %}
{% block title %}
    Финансовые инструменты
{% endblock %}

{% block content %}
  <h1>Финансовые инструменты</h1>
  {% for symbol_info in symbol_infos %}
    <article>
      <p>{{ symbol_info.name }}</p>
      <ul>
        <li>
          Рынок:
          <a href="{% url 'markets:market' symbol_info.market.name %}">
            {{ symbol_info.market.name }}
          </a>
        </li>
        <li>Лот: {{ symbol_info.lot_size }}</li>
      </ul>
    </article>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% endblock %}

symbolinfo/templates/markets/market.html
{% extends 'base.html' %}
{% block title %}
  {{ market.name }}
{% endblock %}

{% block content %}
  <h1>{{ market.name }}</h1>
  {% for symbol_info in symbol_infos %}
    <article>
      <p>{{ symbol_info.name }}</p>
      <ul>
        <li>
          Рынок:
          <a href="{% url 'markets:market' symbol_info.market.name %}">
            {{ market.name }}
          </a>
        </li>
        <li>Лот: {{ symbol_info.lot_size }}</li>
      </ul>
    </article>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% endblock %}